# Site settings
baseurl = "https://dandua.com"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

author = "Danish Dua"
title = "Danish Dua"

contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"

enableRobotsTXT = true

# Copyright
copyright = "&copy; 2023 Danish Dua"

[params]

  # Metadata for search engines and social sharing
  author = "Danish Dua"
  description = "Danish Dua's Portfolio"
  keywords = "Danish,Dua,Danish Dua,Software,Developer,blog,Dan Dua,Programmer"
  twitterHandle = "dandua98"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"


  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:danish@dandua.com"

      [[params.links.list1.link]]
        text = "LinkedIn"
        url = "https://linkedin.com/in/dandua98"

      [[params.links.list1.link]]
        text = "Github"
        url = "https://github.com/dandua98"
